name: Release

on:
  push:
    tags:
      - 'v**'

jobs:
  build:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        if: ${{ !env.ACT }}
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Gradle Wrapper Validation
        uses: gradle/actions/wrapper-validation@v3

      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'ru.dadyarri.jks'
          fileDir: '${{ github.workspace }}/app/keystore/'
          encodedString: ${{ secrets.KEYSTORE }}

      - name: Decode google-services.json
        id: decode_google
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'google-services.json'
          fileDir: "${{ github.workspace }}/app/src/"
          encodedString: ${{ secrets.GOOGLE_SERVICES }}

      - name: Build APK
        run: ./gradlew clean :app:assembleRelease -x test --no-daemon
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}

      - name: Verify Signature
        run: |
          $ANDROID_SDK_ROOT/build-tools/33.0.1/apksigner verify --print-certs "${{ github.workspace }}/app/build/outputs/apk/release/ChocoManager.apk"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: "${{ github.workspace }}/app/build/outputs/apk/release/ChocoManager.apk"


  changelog:
    runs-on: ubuntu-latest
    outputs:
      release_body: ${{ steps.git-cliff.outputs.content }}
      version: ${{ steps.git-cliff.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate a changelog
        uses: orhun/git-cliff-action@v3
        id: git-cliff
        with:
          config: cliff.toml
          args: -vv --latest --strip header
        env:
          OUTPUT: CHANGES.md
          GITHUB_REPO: ${{ github.repository }}
          
  release:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    needs:
      - changelog
      - build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0


      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app
          path: "${{ github.workspace }}/dist/ChocoManager.apk"

      - name: List files
        run: |
          ls "${{ github.workspace }}"
          echo "---"
          ls "${{ github.workspace }}/dist"

      - name: Create Release
        if: ${{ !env.ACT }}
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          body: ${{ needs.changelog.outputs.release_body }}
          name: "Версия ${{ needs.changelog.outputs.version }}"
          files: "${{ github.workspace }}/dist/ChocoManager.apk"